### ISSUE TITLE
06 - 04 - Roshambo!

### ISSUE THREAD

**Issue by AbeEveland** [AbeEveland/assignments#25]
Create a Roshambo (Rock-Paper-Scissors) game.

## Objectives

- Work with JavaScript and the DOM
- Practice conditional logic

### Background

See the Wikipedia page about
[Rock, Paper, Scissors](https://en.wikipedia.org/wiki/Rock%E2%80%93paper%E2%80%93scissors)

### How to get started

- Get familiar with rock, paper, scissors if you haven't played before (or in a while)
- Draw out on paper/whiteboard/computer the rough design of your application
  - See _Explorer Mode_ for the UI requirements
- Start by placing all the HTML elements on the page
- Style the user interface
- Write out in English, ALL the steps the application needs to take
  - For example "When user one clicks on Rock, remember that user one chooses
    Rock"

#### Part 1

> NOTE: Complete part 1 before moving on to part 2

- [ ] There should be three buttons for Player One: Rock, Paper, Scissors
- [ ] There should be three buttons for Player Two: Rock, Paper, Scissors
- [ ] Player One should be able to select their throw
- [ ] Player Two should be able to select their throw
- [ ] After both players make their selection, I should be told who won and the game should be over.

#### Part 2

- [ ] You have heard about _Rock, Paper, Scissors_, but have you tried
      [_Rock, Paper, Scissors, Lizard, Spock_](https://bigbangtheory.fandom.com/wiki/Rock,_Paper,_Scissors,_Lizard,_Spock)?
      Modify your game to allow the extra options!
- [ ] Have fun with the CSS by adding colors, animations, and effects to make the
      game more enjoyable

### Part 3

- [ ] Find at least THREE codewar you have not completed from our daily warmups and complete them. If you don't have THREE incomplete codewar warmups, find some new ones to tackle. I encourage for those who want an extra level of challenge, just let me know which codewar you are solving.
- [ ] For each, copy your solution into a gist:  See https://gist.gitub.com and include those links in your homework comment.

### Adventure Mode

- [ ] Your game is currently only 1 vs 1, add the ability to add more computer or users players to the game

**Comment by AbeEveland** [comment]
using System;

public class Kata
    {
        public  static int Opposite( int number)
        {
        return -number;




        
        }
    }

**Comment by AbeEveland** [comment]
using System;
using System.Linq;

public class Kata
{
  public static int PositiveSum(int[] arr)
  {

    return arr.Where(x => x > 0).Sum();

   
    
  }
}

**Comment by AbeEveland** [comment]
using System;

public static class Kata 
{
    public static int summation(int num)
    {
      return num*(num+1)/2;
    }
}

**Comment by AbeEveland** [comment]
https://github.com/AbeEveland/roshambo

**Comment by AbeEveland** [comment]
https://github.com/AbeEveland/roshambo

**Comment by AbeEveland** [comment]
Your homework **06 - 04 - Roshambo!** was marked: **Meets Expectations**


![Ring that bell!](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBTQT09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--fabcecd7c921cc4014bfcce0bd127f9e89ef3986/meets-2.gif)
> &ldquo;Ring that bell!&rdquo;

**Comment by gstark** [comment]
Great work!
